### ISSUE TITLE
Chinese cr settings only show as ???

### ISSUE THREAD

**Issue by ailin-nemui** [blchinezu/pocketbook-coolreader#115]
When opening the settings in Chinese locale, my CR3 only shows ??? instead of the settings text. I guess it must be a font issue, any idea about this problem?

Btw, System UI shows Chinese correctly and I put a bunch of Chinese fonts on the device as well

**Comment by blchinezu** [comment]
Duplicate: https://github.com/blchinezu/pocketbook-coolreader/issues/86

**Comment by blchinezu** [comment]
I think it's an encoding issue or something. No Chinese characters are shown in CR3. Didn't figure it out yet.
