### ISSUE TITLE
Text aligment "justify" in style settings

### ISSUE THREAD

**Issue by Pokec** [blchinezu/pocketbook-coolreader#154]
Style settings/Default paragraph formating/Text aligment : Justify 
This settings not works, text is formated as left.
("styles.def.align=text-align: justify")

**Comment by blchinezu** [comment]
It's working fine for me. You probably use embedded styles too and those might overwrite your settings.
I always keep embedded styles deactivated especially since some of them might create problems.
Some ebook styles even crash CR.

**Comment by Pokec** [comment]
I keep embeded styles deactivated too, but "Default paragraph formatting/text alignment/Justify" in CoolReader 3 works as "left" for me with all books.

My device:
PocketBook 626 Touch Lux 3 
firmware W626.5.9.360)

CoolReader:
Version: 0.0.6-17-43
Date:    2015-08-29
Build:   pro5
Branch:  master

But if it works fine in your device, please, forget about it, problem is somewhere in my settings, maybe. Your modifications of CoolReader for PocketBooks is GREAT in functionality and design, thank you very much for your time and enthusiasm.

**Comment by blchinezu** [comment]
Hmm.. Strange. It's working fine with all my books. I've attached my current config. Maybe it helps.
[cr3.ini.txt](https://github.com/blchinezu/pocketbook-coolreader/files/6179/cr3.ini.txt)

**Comment by Pokec** [comment]
With your config it works right on my device too. Thank you very much for it. Here is content of my problematic config, but only for information. THANKS one more time for all :-)

app.skin.file=pb626fw5
app.tapzone.action.tap.1=GO_LINK
app.tapzone.action.tap.2=QUICK_MENU
app.tapzone.action.tap.3=PB_STATUS_LINE
app.tapzone.action.tap.4=PAGE_UP
app.tapzone.action.tap.5=QUICK_MENU
app.tapzone.action.tap.6=PAGE_DOWN
app.tapzone.action.tap.7=PAGE_UP
app.tapzone.action.tap.8=PB_CONTENTS
app.tapzone.action.tap.9=PAGE_DOWN
app.tapzone.action.tap.long.1=GO_FIRST
app.tapzone.action.tap.long.2=PB_STATUS_LINE
app.tapzone.action.tap.long.3=GO_LAST
app.tapzone.action.tap.long.4=PAGE_UP_10
app.tapzone.action.tap.long.5=MAIN_MENU
app.tapzone.action.tap.long.6=PAGE_DOWN_10
app.tapzone.action.tap.long.7=PAGE_UP_10
app.tapzone.action.tap.long.8=EXIT
app.tapzone.action.tap.long.9=PAGE_DOWN_10
app.tapzone.height.1=33
app.tapzone.height.2=33
app.tapzone.width.1=33
app.tapzone.width.2=33
background.color.default=0x00FFFFFF
cr3.file.props.font.size=22
cr3.pocketbook.buffer.bpp=0
cr3.pocketbook.dictionary=English-Czech GNU-FDL
cr3.pocketbook.orientation=0
crengine.autosave.bookmarks=1
crengine.bookmarks.icons=0
crengine.cache.filesize.min=300000
crengine.cache.forced.filesize.min=65536
crengine.display.full.update.interval=0
crengine.display.inverse=0
crengine.display.standby=10
crengine.display.turbo.update=0
crengine.doc.embedded.fonts.enabled=0
crengine.doc.embedded.styles.enabled=0
crengine.file.txt.preformatted=0
crengine.font.fallback.face=Liberation Sans
crengine.font.size=26
crengine.footnotes=1
crengine.highlight.bookmarks=1
crengine.highlight.bookmarks.color.comment=#a08020
crengine.highlight.bookmarks.color.correction=#a04040
crengine.highlight.selection.color=#c0c0c0
crengine.hyphenation.directory=Czech_hyphen_(Alan).pdb
crengine.image.scaling.zoomin.block.mode=2
crengine.image.scaling.zoomin.block.scale=2
crengine.image.scaling.zoomin.inline.mode=2
crengine.image.scaling.zoomin.inline.scale=0
crengine.image.scaling.zoomout.block.mode=2
crengine.image.scaling.zoomout.block.scale=2
crengine.image.scaling.zoomout.inline.mode=2
crengine.image.scaling.zoomout.inline.scale=0
crengine.interline.space=100
crengine.page.header.chapter.marks=1
crengine.page.header.font.color=0xFF000000
crengine.page.header.font.embolden=0
crengine.page.header.font.face=Arial Narrow, Arial, DejaVu Sans
crengine.page.header.font.size=22
crengine.page.margin.bottom=10
crengine.page.margin.left=16
crengine.page.margin.right=16
crengine.page.margin.top=20
crengine.page.view.mode=1
crengine.progress.show.first.page=1
crengine.style.floating.punctuation.enabled=0
crengine.style.space.condensing.percent=100
crengine.style.space.expanding.percent=100
crengine.style.tracking=0
font.antialiasing.mode=2
font.color.default=0x00000000
font.embolding=0
font.face.default=Liberation Sans
font.face.weight.embolden=0
font.gamma=1.00
font.hinting.mode=2
font.kerning.enabled=0
styles.annotation.align=text-align: justify
styles.annotation.font-size=font-size: 90%
styles.annotation.font-style=font-style: italic
styles.annotation.margin-left=margin-left: 1em
styles.annotation.margin-right=margin-right: 1em
styles.annotation.text-indent=text-indent: 1.2em
styles.cite.align=text-align: justify
styles.cite.font-style=font-style: italic
styles.cite.margin-bottom=margin-bottom: 0.3em
styles.cite.margin-left=margin-left: 1em
styles.cite.margin-right=margin-right: 1em
styles.cite.margin-top=margin-top: 0.3em
styles.cite.text-indent=text-indent: 1.2em
styles.def.align=text-align: justify
styles.def.font-face=font-family: Literata
styles.def.letter-spacing=
styles.def.margin-bottom=margin-bottom: 0.2em
styles.def.margin-left=margin-left: 0em
styles.def.margin-right=margin-right: 0em
styles.def.margin-top=margin-top: 0em
styles.def.text-indent=text-indent: 1.2em
styles.epigraph.align=text-align: left
styles.epigraph.font-style=font-style: italic
styles.epigraph.margin-bottom=margin-bottom: 0.3em
styles.epigraph.margin-left=margin-left: 15%
styles.epigraph.margin-right=margin-right: 1em
styles.epigraph.margin-top=margin-top: 0.3em
styles.epigraph.text-indent=text-indent: 1.2em
styles.footnote=font-size: 70%
styles.footnote-link.font-size=font-size: 70%
styles.footnote-link.vertical-align=vertical-align: super
styles.footnote-title=font-size: 110%
styles.link.text-decoration=text-decoration: underline
styles.poem.align=text-align: left
styles.poem.font-style=font-style: italic
styles.poem.margin-bottom=margin-bottom: 0.3em
styles.poem.margin-left=margin-left: 15%
styles.poem.margin-right=margin-right: 1em
styles.poem.margin-top=margin-top: 0.3em
styles.poem.text-indent=text-indent: 0em
styles.pre.align=text-align: left
styles.pre.font-face=font-family: "Courier New", "Courier", monospace
styles.pre.margin-bottom=margin-bottom: 0em
styles.pre.margin-left=margin-left: 0em
styles.pre.margin-right=margin-right: 0em
styles.pre.margin-top=margin-top: 0em
styles.pre.text-indent=text-indent: 0em
styles.subtitle.align=text-align: left
styles.subtitle.font-size=font-size: 110%
styles.subtitle.font-style=font-style: normal
styles.subtitle.font-weight=font-weight: bolder
styles.subtitle.margin-bottom=margin-bottom: 0.2em
styles.subtitle.margin-top=margin-top: 0.2em
styles.subtitle.text-indent=text-indent: 0em
styles.text-author.font-style=font-style: italic
styles.text-author.font-weight=font-weight: bolder
styles.text-author.margin-left=margin-left: 1em
styles.title.align=text-align: left
styles.title.font-size=font-size: 115%
styles.title.font-weight=font-weight: bolder
styles.title.margin-bottom=margin-bottom: 0.3em
styles.title.margin-left=margin-left: 0em
styles.title.margin-right=margin-right: 0em
styles.title.margin-top=margin-top: 0.3em
styles.title.text-indent=text-indent: 0em
window.landscape.pages=1
window.pinch.zoom=1
window.status.battery=1
window.status.battery.percent=1
window.status.clock=1
window.status.clock.format=0
window.status.line=0
window.status.pos.chapter.page.remains=0
window.status.pos.page.count=1
window.status.pos.page.number=1
window.status.pos.percent=0
window.status.title=1
window.swipes.frontlight=2
window.swipes.pageturn=1
