### ISSUE TITLE
In settings, cannot move to another page/scroll with 630 (Sense)

### ISSUE THREAD

**Issue by Dissimilis** [blchinezu/pocketbook-coolreader#176]
I can see that there are more pages in some settings but swiping or using next/prev buttons doesn't work.
Using Pocketbook Sense (630)

![scr0001](https://cloud.githubusercontent.com/assets/7642759/11906903/91dd0616-a5d8-11e5-83c1-f928f132ce5f.png)

**Comment by Dissimilis** [comment]
Manual fix (for PB630/Sense):
Edit /system/share/cr3/keymaps/keymaps.ini under category [menu] like this:
KEY_NEXT = MCMD_NEXT_PAGE
KEY_PREV = MCMD_PREV_PAGE
This will enable settings navigation with HW buttons.

**Comment by blchinezu** [comment]
you should definitely use pb626fw5 skin since it's optimised for your resolution.
