### ISSUE TITLE
Support for touch only devices

### ISSUE THREAD

**Issue by Dissimilis** [blchinezu/pocketbook-coolreader#177]
From message at the bottom (OK - Set button) I assume that support for devices without physical buttons is non existing. 
Most essential place whe touch support is neaded - dictionary.
Using Pocketbook Sense (630)

![scr0002](https://cloud.githubusercontent.com/assets/7642759/11906957/f86df50c-a5d8-11e5-82ab-b610c9fe9f44.png)

**Comment by blchinezu** [comment]
here you have the same problem. change the skin. i never use the physical buttons. :)

**Comment by blchinezu** [comment]
also... sorry for the late response. for some reason I didn't see the notifications from github.
