### ISSUE TITLE
Add possibility to open book in coolreader

### ISSUE THREAD

**Issue by msmolka** [blchinezu/pocketbook-coolreader#178]
Currently when you choose open book in FB reader, by holding touch and open menu, there is no possibility to open this book in cool reader. At least I didn't find the way of doing that. It would be good to have possibility to open book directly from cool reader, or from menu, or by restore all books to default.

**Comment by ghmajx** [comment]
I just find out how to restore the default open with method defined in extensions.cfg. Delete the system\config\handlers.cfg file, then it will be ok.

**Comment by blchinezu** [comment]
https://github.com/msmolka
This isn't really related to CR.

https://github.com/ghmajx
You can place the file from this archive in the applications folder:
[resetOpenWith.app.zip](https://github.com/blchinezu/pocketbook-coolreader/files/371611/resetOpenWith.app.zip)

When you want to reset the "Open with" settings just run the app from the menu and reboot the device (Or connect the device to your PC - not just as charging - and then disconnect. This will kill the library app and reload configs)
