### ISSUE TITLE
My selected theme will be reset to default by CoolReader

### ISSUE THREAD

**Issue by keinejiang** [blchinezu/pocketbook-coolreader#184]
I create a new theme for my PocketBook InkPad (PB840) and apply it. But the default theme will be applied when I enter CoolReader.

**Comment by blchinezu** [comment]
Deactivate through: **Settings** > **Display settings** > **Custom system theme**

**Comment by keinejiang** [comment]
Hi, the "Custom System Theme" had been deactivated. The problem is still here.

And theme is reset to default "Line" theme, not your "LineCustom.pbt".

**Comment by keinejiang** [comment]
I test the "Custom System Theme" option. This issue is here after I deactivate it. I guess CR3 would restore all 3-party themes to "Line" when it detects the deactivation of this option.

**Comment by blchinezu** [comment]
I'll check the code.

**Comment by blchinezu** [comment]
Please test this build: https://github.com/blchinezu/pocketbook-coolreader/raw/dev/builds/626/pro5/latest.zip

**Comment by keinejiang** [comment]
This issue has been solved in this build.

**Comment by blchinezu** [comment]
Ok. Thanks.

**Comment by blchinezu** [comment]
Fixed with https://github.com/blchinezu/pocketbook-coolreader/commit/276d90d572ca244f633f44306bfc8f628f0674fc
