### ISSUE TITLE
Css with display:none

### ISSUE THREAD

**Issue by msmolka** [blchinezu/pocketbook-coolreader#228]
Hello,
I'm changing my ebooks and setting some parts with style that have set display:none. However I've noticed that such elements are still displayed in cool reader when I disable document internal styles. I'm disabling styles because I don't like each book different font, font size, font family. However I still would like to have hidden things hidden.

So is there any way to have my own font but other styles persisted?

**Comment by blchinezu** [comment]
I don't think you can do that. In my opinion things work as they should since CR removes all styling. Why don't you just remove what you want to hide from the book?
