### ISSUE TITLE
Unable to open epubs after update to lastest version

### ISSUE THREAD

**Issue by ArchCarrier** [blchinezu/pocketbook-coolreader#243]
I have a PocketBook Aqua, firmware version W640.4.4.1852. I just updated CoolReader to v0.0.6-17-62. Now I'm unable to open any books in CoolReader. There is a file `cr3-pb.crash.log` in `/system/` that says:
```
/mnt/ext1/system/share/cr3/bin/cr3-pb.app: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
```
I hope you can fix this.

**Comment by blchinezu** [comment]
That's strange... 
Which was the previous working version?
Did you install the pro4 release?

**Comment by ArchCarrier** [comment]
I don't remember what the previous version was, but I hadn't updated in a while. I just went back to 6-17-61, and it has the same problem. I have the pro4 release.

**Comment by blchinezu** [comment]
Knowing which is the last working version would be very helpful. I could track the particular changes made in that update and figure what could cause the problem.

**Comment by ArchCarrier** [comment]
Well this is very annoying. I'm back at 0.0.6-17-23 and it still doesn't work. I even did a factory reset and still nothing. I did update the PB firmware today, so that might be the cause (my old firmware was from 2014).

**Comment by blchinezu** [comment]
Hmm... That might be an issue.

**Comment by ArchCarrier** [comment]
I reinstalled the latest firmware, and I noticed two lines during the update process:
```
Unknown image type: a
Unknown image type: s
```

**Comment by blchinezu** [comment]
Try this buid. I've compiled the jpeg library into CR3.
[cr3-v0.0.6-17-62.1b-pro4.zip](https://github.com/blchinezu/pocketbook-coolreader/files/1720558/cr3-v0.0.6-17-62.1b-pro4.zip)

**Comment by ArchCarrier** [comment]
Fantastic, that works! Thank you!

**Comment by blchinezu** [comment]
Ok, I'll push an update with this change.

**Comment by blchinezu** [comment]
Done: https://github.com/blchinezu/pocketbook-coolreader/releases/tag/v0.0.6-17-62.1
