### ISSUE TITLE
Pocketbook 740 pro doesn't see CoolReader

### ISSUE THREAD

**Issue by xahon** [blchinezu/pocketbook-coolreader#254]
I dropped everything from release zip, no coolreader entry in "open with" menu had appeared

**Comment by samiraguiar** [comment]
You also have to copy the `cr3-pb.app` file to `/applications/` and the app will be displayed in the app panel. To make books open with the app you also have to copy the `extensions.cfg` file. On my tests, however, the font size was huge and I couldn't find a way to make it smaller than 124.

edit: found it. You have to edit `/system/config/cr3/cr3.ini`, value `crengine.font.size` (I think this file gets created once the app is run). A font size of 44 was good enough. However, changing it like this seems impractical, so I guess the application is not optimised for this device.

**Comment by Uwe-B** [comment]
Just pinch the font smaller in an open book.

**Comment by xahon** [comment]
thanks @samiraguiar, sorry, i forgot to close the issue
