### ISSUE TITLE
The book cover on the "document properties" page

### ISSUE THREAD

**Issue by maslukov** [blchinezu/pocketbook-coolreader#36]
Displays a thumbnail of the book cover on the information page.

**Comment by blchinezu** [comment]
What information page?

**Comment by maslukov** [comment]
blchinezu: "What information page?"

I meane the "document properties" page.

**Comment by blchinezu** [comment]
You mean the **Main menu** > **About** page?

**Comment by maslukov** [comment]
Exactly, "Main menu > About"!

**Comment by blchinezu** [comment]
I don't see why we would do that.

**Comment by maslukov** [comment]
I think this is a good way to reports of visual information (and, in fact, it adds even more informativeness). In addition, it can be very aesthetically pleasing. I think many users it will might like.

**Comment by blchinezu** [comment]
Maybe. But I don't think there are many users that even open the **About** window.
