### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by druss67** [blchinezu/pocketbook-coolreader#62]
I translate the application in French manually. I mean, when I use the CR and see an entry not translated I add it into the fr.mo. It will be nice if the translation will be handle more professionally with usage of a translation web app like Transifex or something like this. If this is not possible can you tell me where I can fine all the entries used by the app ?

**Comment by blchinezu** [comment]
For the moment there's no solution. The same thing crossed my mind last night. I'll have to automate the **.pot** generation.

**Comment by blchinezu** [comment]
This will be the link: https://www.transifex.com/projects/p/coolreader-pocketbook/
Now I have to automate the **.pot** generation.

**Comment by blchinezu** [comment]
Done: https://github.com/blchinezu/pocketbook-coolreader/commit/ed7c9e0643eba6c254a50a98a5b7f67d0c449866

The transifex page is the one already stated: https://www.transifex.com/projects/p/coolreader-pocketbook/
