### ISSUE TITLE
CoolReader forgets Reading Position, starts at page 1

### ISSUE THREAD

**Issue by ailin-nemui** [blchinezu/pocketbook-coolreader#83]
hi, I'm using Cool Reader on the Touch Lux 3 with Firmware 5.7 and very much like it. However I'm having one grave issue, sometimes the Reader forgets where I read into a book. When I start the reader again (with the power button), it opens the last read book on the cover page and I cannot find back to my previous reading position. It seems to occur when the device turns off itself after delay (10 minutes in default setting), but also not always.

Did anyone else experience this problem or has an idea how to resolve it??

**Comment by blchinezu** [comment]
That's strange. I have the Touch Lux 2 with FW5.7 and that doesn't happen. In theory, the only difference between the devices are the screen and the driver managing the screen. So that should happen on both devices. But it's not.

**Comment by ailin-nemui** [comment]
yea, it doesn't *always* happen. it's also a bit strange to me... when you have any idea what I could try, let me know. if I figure out anything more I'll also post here.

**Comment by blchinezu** [comment]
I have no idea how could I help. Hopefully someone will figure a pattern regarding the action that actually causes the page reset.

**Comment by blchinezu** [comment]
I just placed an order for Touch Lux 3. So there are some chances of figuring out this bug. :)

**Comment by ailin-nemui** [comment]
Hi,

in my usage in the last days, it has only happened one out of like 20 times. maybe this bug needs to go under the rare unresolved mysteries after all. It's a bit weird, this issue happened much more frequently when I reported this bug.

**Comment by blchinezu** [comment]
Now that's interesting... I compared the Touch Lux 2 and Touch Lux 3 FW5.7 download links from pocketbook support page and they're identical. Like... Identical. Which means both devices actually have the exact same firmware software.

**Comment by ailin-nemui** [comment]
curious, did you up your TL3 to firmware 5.8?

On the bug, now I also had this happen with manual shut-down (long press of power button) inside CR3. It also doesn't start from page 1 this time, but from page 27 (which may have been the last reading position when the system shut down before) :cry:

**Comment by blchinezu** [comment]
Yes, I updated to 5.8.
I still didn't encounter your kind of issue. I usually let it shut down by itself but I also powered it off manually once in a while. No problems.
It seems though that the OTA Update doesn't work with the latest wireless enhancements.

**Comment by ailin-nemui** [comment]
I wonder if my particular PocketBook could be broken in some way. But I guess the support would not care about third party apps... maybe I need to test with the built-in reader for a while

**Comment by blchinezu** [comment]
I doubt it's a hardware problem.

**Comment by blchinezu** [comment]
Does it still happen?

**Comment by ailin-nemui** [comment]
It is still happing occasionally.. it was happening frequently when I got the device, but later on only about 1 in 100 times or even less frequent with the 5.8 firmware. (it just happened again though)

I installed 5.9 just now and will keep observing... I guess there is little sense for this mystery bug to remain open, thanks for your concern.

**Comment by blchinezu** [comment]
The thing still never happened to me. Strange.
