### ISSUE TITLE
Chinese is shown as question marks

### ISSUE THREAD

**Issue by blchinezu** [blchinezu/pocketbook-coolreader#86]
Font? Encoding?

The .mo file look fine.

**Comment by blchinezu** [comment]
@ailin-nemui
Can you give me a Chinese font?

I've logged the i18n translation and it's getting the correct strings:

    133 fonts loaded.
    CRMoFileTranslator::getText("[No Hyphenation]"): "不使用断字"
    CRI18NTranslator::translate("[No Hyphenation]"): "不使用断字"
    CRMoFileTranslator::getText("[Algorythmic Hyphenation]"): "算法断字"
    CRI18NTranslator::translate("[Algorythmic Hyphenation]"): "算法断字"
    [...]

**Comment by ailin-nemui** [comment]
The mo/po files seem to be UTF-8 proper, just like the other language files. The characters also show correctly on a computer. You can download the "WenQuanYi Micro Hei" font from http://sourceforge.net/projects/wqy/files/wqy-microhei/0.2.0-beta/ (Github does not allow me to stick it to this post) but I don't know if it can help you?

**Comment by ailin-nemui** [comment]
My only idea would be that CR3 tries to load some font for the settings-menu, which does not contain any Chinese letters / does not search for alternate fonts on the system if needed. On regular Computers, the modern graphical systems do "font substitution" where they load characters from other fonts if the current font does not contain them. It does not seem like the Pocketbook can do this.

**Comment by pkb** [comment]
CR3 supports fallback font (i.e. font which is used when some chars missing in the main font). I don't remember exactly, but I think it affects not only ebook content but also UI elements. Can you check what is specified in the "crengine.font.fallback.face" in the cr3.ini? Can you set fallback font using settings or by manually editing the cr3.ini, if so can you set "WenQuanYi Micro Hei" as the fallback font?

**Comment by blchinezu** [comment]
crengine.font.fallback.face=DejaVu Sans

**Comment by blchinezu** [comment]
I can't test right now but I'll try changing the skin. The fallback font from cr3.ini is for the ebook as far as I know.
The skins define menus font:

    <text color="#000000" face="Liberation Sans, DejaVu Sans" size="22" bold="true" italic="false" valign="center" halign="center"/>

**Comment by blchinezu** [comment]
The font is the problem. Do you have any idea which system font is used for Chinese?

**Comment by ailin-nemui** [comment]
it looks like AR PL New Sung, but I'm not 100% sure

**Comment by blchinezu** [comment]
Ok. I'll test,

**Comment by blchinezu** [comment]
Confirmed. That's it.

**Comment by ailin-nemui** [comment]
cool :+1:

**Comment by blchinezu** [comment]
It seems like the skin file doesn't entirely fix the issue. There still are strings that don't use the desired font.
So I force the "AR PL New Sung" font when current language is Chinese regardless of the skin settings.
I'll release this fix today.
